// Generated by ReScript, PLEASE EDIT WITH CARE


var count = {
  contents: 0
};

function renderCountTextView(n) {
  var el = document.getElementById("count");
  el.innerText = "Count is " + String(n);
  
}

function updateCount(steps) {
  count.contents = steps + count.contents | 0;
  
}

function renderView(steps) {
  updateCount(steps);
  var el = document.getElementById("count");
  if (count.contents > 0) {
    el.className = "count count-positive";
  } else if (count.contents < 0) {
    el.className = "count count-negative";
  } else {
    el.className = "count count-zero";
  }
  return renderCountTextView(count.contents);
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

var plusButton = document.getElementById("plus-one");

plusButton.addEventListener("click", plusOne);

var minusButton = document.getElementById("minus-one");

minusButton.addEventListener("click", minusOne);

export {
  count ,
  renderCountTextView ,
  updateCount ,
  renderView ,
  plusOne ,
  minusOne ,
  plusButton ,
  minusButton ,
  
}
/* plusButton Not a pure module */
